// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJzurNHrS9KxXiC0K37PZL2wPEgS0uePI',
    appId: '1:805204885648:web:3f4602f912519d066fd815',
    messagingSenderId: '805204885648',
    projectId: 'alu-internship-platform',
    authDomain: 'alu-internship-platform.firebaseapp.com',
    storageBucket: 'alu-internship-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqelkV-ooDEvNQevXeAdeEdcH0w7kAgw',
    appId: '1:805204885648:android:5a09e9a3064a3c516fd815',
    messagingSenderId: '805204885648',
    projectId: 'alu-internship-platform',
    storageBucket: 'alu-internship-platform.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcDFnGQS_7yz-x6nngsVf45kUhWHYvtpY',
    appId: '1:805204885648:ios:8c6945a5d0eab13d6fd815',
    messagingSenderId: '805204885648',
    projectId: 'alu-internship-platform',
    storageBucket: 'alu-internship-platform.firebasestorage.app',
    iosClientId: '805204885648-44hd537vkb7gmsupmep9rp2oq6hh52rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aluEnternershipPro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcDFnGQS_7yz-x6nngsVf45kUhWHYvtpY',
    appId: '1:805204885648:ios:8c6945a5d0eab13d6fd815',
    messagingSenderId: '805204885648',
    projectId: 'alu-internship-platform',
    storageBucket: 'alu-internship-platform.firebasestorage.app',
    iosClientId: '805204885648-44hd537vkb7gmsupmep9rp2oq6hh52rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aluEnternershipPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJzurNHrS9KxXiC0K37PZL2wPEgS0uePI',
    appId: '1:805204885648:web:e25ce04a1f3e1b446fd815',
    messagingSenderId: '805204885648',
    projectId: 'alu-internship-platform',
    authDomain: 'alu-internship-platform.firebaseapp.com',
    storageBucket: 'alu-internship-platform.firebasestorage.app',
  );
}
